### ISSUE TITLE
openbiox 官方论坛使用说明

### ISSUE THREAD

**Issue by Miachol** [openbiox/openbiox-flarum#1]
## 使用人群

- 全体 openbiox 成员
- 所有希望申请加入 openbiox 的朋友

## 使用语言

- 中文为主，英文为辅
- 同一个帖子应保持语言的一致性

## 论坛功能

- 实践项目相关的交流
- 资源分享
- 项目人员招募

## 注意事项

1. 不得发布违法虚假信息
2. 不得发布辱骂性言论
3. 如果是进行提问，请在提问之前阅读[提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)。对于不符合要求的提问，我们会直接删除。
4. 不得恶意顶贴

## 管理员

- @Miachol 
- @ShixiangWang 
- @Hellenzz 
- @ytdai 
- @yangyangclover 
- @jmzeng1314 
- @WenlongShen 
- @rafael1314
- @xxmen
- @ChrisLou-bioinfo
- @xchromosome219
- @Jinzeng-Wang
- @wang-qi-wang
- @wupengss
- @hyacz
- @fei0810
- @zhaoqingbo1993

**Comment by ShixiangWang** [comment]
整个 https://community.rstudio.com/ 论坛会不会更好？

**Comment by Miachol** [comment]
> 整个 https://community.rstudio.com/ 论坛会不会更好？

https://community.openbiox.org/
