### ISSUE TITLE
playcloud 公共交流区

### ISSUE THREAD

**Issue by Miachol** [openbiox/openbiox-flarum#2]
## playcloud 简介

旨在通过主题学习、提出问题、解决问题、终极考验等方式锻炼成员的 Linux基本操作、Git版本管理操作，积累网页服务器的运维经验、提高 Bash/R/Python 等编程语言的实践运用能力。

## 项目看板

https://github.com/orgs/openbiox/projects/9

## 团队内部交流

https://github.com/orgs/openbiox/teams/playcloud

## 学习资源

- Linux and Shell：https://github.com/openbiox/playcloud/issues/2
- Web service 开发基础：https://github.com/openbiox/playcloud/issues/3
- 静态文档/博客系统及网页服务运维基础 ：https://github.com/openbiox/playcloud/issues/5

## 问题清单

- Linux and Shell：https://github.com/openbiox/playcloud/issues/1
- Web service 开发基础：https://github.com/openbiox/playcloud/issues/4
- 静态文档/博客系统及网页服务运维基础 ：https://github.com/openbiox/playcloud/issues/6

## 本 chatroom 功能

为 playcloud 团队成员/想参与 playcloud 项目活动的非团队成员提供一个公共的交流场所

**Comment by Miachol** [comment]
@Byronxy @lixin856 @Siaokie 因为 assigness 最多只能有 10 个人，我就不指定你们了

**Comment by xchromosome219** [comment]
Noted with Thanks

**Comment by Miachol** [comment]
请大家在明天结束之前在 https://github.com/openbiox/playcloud/issues/4 提交与【云服务器购买和配置、HTML/CSS/JavaScript 基础、Git 和 GitHub 入门、MySQL 和 SQLite 语言基础】有关的简答题和编程练习题。

2019 年 5 月 6 日晚上，[问题清单](https://github.com/openbiox/playcloud/issues/4) 会作为主题学习周第三次活动进行发布。

在编程题部分如果有一些好的项目 idea ，可以有提升为团体/社区维护项目的机会。

**Comment by Miachol** [comment]
已经发布后面一个月的学习主题，大家注意查收：<https://github.com/openbiox/playcloud/issues/5>。建议结合自己做的实际项目来学习和练习，学以致用（比如自己的博客、知识库、或者自己维护的项目文档/报告系统）。

**Comment by Miachol** [comment]
已迁移至：https://community.openbiox.org/d/21-public-channel-of-the-playcloud-team
