### ISSUE TITLE
openbiox 开放项目： bioinformatics-100-days 项目负责人招募

### ISSUE THREAD

**Issue by Miachol** [openbiox/openbiox-flarum#4]
**参与人员要求：** 

- 可以是非 openbiox 成员
- openbiox 成员则需要满足：未参与其他实践项目、或者参与的实践项目工作量均较少

**主要内容：** 在 100 天之内每天至少利用半个小时学习和更新各类生物信息学数据分析实例和代码，并至少完成 [The Bioconductor 2018 Workshop Compilation](https://bioconductor.github.io/BiocWorkshops/) 的学习和代码内容扩展与练习。

**仓库地址：** <https://github.com/openbiox/bioinformatics-100-days>

**Comment by dandanpeng** [comment]
报名。
计算生物学与生物信息硕士在读（二年级），本科毕业论文中的一部分数据分析工作包括RNA-Seq，Hi-C原始数据处理和分析，此外读研期间上过高通量数据分析处理、数据挖掘和机器学习相关的课程，也通过课程项目积累了一些经验。浏览了The Bioconductor 2018 Workshop Compilation的目录，认为自己目前掌握的技能和bioinformatics-100-days项目要求挺吻合的，学习曲线应该会比较平缓。
目前在进行实验室轮转，参与蛋白质序列设计的项目，每周只有两门课程，所以可自由支配的时间比较多，能够满足每天利用半小时负责项目的要求。
