### ISSUE TITLE
openbiox 开放项目：自然语言处理（机器学习方向）与科学文献信息提取技术学习/实践小组

### ISSUE THREAD

**Issue by Miachol** [openbiox/openbiox-flarum#6]
> 数据总体上分为结构化和非结构化的数据。结构化的数据是指实体和关系的规范和可预测的组织。大部分的需要处理的数据都属于非结构化的数据。
> 信息提取目前已经应用于很多领域，比如商业智能，简历收获，媒体分析，情感检测，专利检索及电子邮件扫描。当前研究的一个特别重要的领域是提取出电子科学文献的结构化数据，特别是在生物和医学领域。
> https://www.cnblogs.com/no-tears-girl/p/6435283.html

生物学/医学文献常常会涉及到各种复杂的实验体系和特定实验因子处理，以及经过这些处理后产生的各种复合的实验结果。

目前来看，从事相关工作的科研工作者的主要任务可以视为一个三步骤的循环：1）设计产生实验结果的方案（基于前人/自己之前的实验结果） 2）产生这些实验结果（包括准备相关前置的材料/设备或者其他资源）3）与其他科研工作者解释和交流产生的实验结果（面对面的形式、文字（科学论文）/视频等其他非直接接触的媒介形式）

对于绝大多数科研工作者来说，都需要花费大量时间阅读这些包含各类复杂反应体系和实验因子处理的科学文献（其中常常还包含各类具有误导性的或者造假性质的干扰），从中抽提取一些结构化和非结构化数据。如该文章产生的实验结果对应于哪些反应体系（细胞系、动物模型或是人体）、特定反应体系和反应条件所构成的实验处理因子的数量和种类（基因功能研究中常见的如引入突变、过表达基因、沉默基因等等）、这些实验处理因子在各类检测技术测试下的原始（如影像数据；细胞形态学；高通量测序数据的原始格式；细胞系的生存时间、增殖能力；小鼠的存活时间；肿瘤病人的五年生存时间）/处理挖掘后的实验结果（各个因子的相关性和相互作用关系；调控网络；富集程度等等）。

自然语言处理技术正在取得快速发展，使得我们自动整理和归纳科学文献所蕴含的明示或暗示的各类信息变得可能。尤其是在生物和医学领域，相关需求正在变得越来越迫切。

基于前期 openbiox 的实践项目设想，现正式招募在自然语言处理技术相关方向有特长/经验/兴趣的朋友加入 openbiox。我们在获得一定人才数量储备之后，openbiox 将正式建立自然语言处理（机器学习方向）与科学文献信息提取技术学习/实践小组，最终将负责并完成某个特定医学文献信息抽提实践项目。

申请加入方式：发送简历和申请信至  committee@openbiox.org 。

**Comment by hjuinj** [comment]
望加入
对自然语言处理有持续的追踪，了解行之有效的的神经网络架构。做过[biocreative的比赛](https://biocreative.bioinformatics.udel.edu/tasks/biocreative-vi/track-4/)

**Comment by kaigu1990** [comment]
之前有过这个想法，有兴趣但没相关项目经验，希望加入学习该方面的应用

**Comment by lixuenan** [comment]
希望加入这个小组，对机器学习感兴趣

**Comment by wupengss** [comment]
申请加入，有很好的机器学习方向基础，Python编程熟练

**Comment by WenlongShen** [comment]
申请加入，希望能加强机器学习方面的技能

**Comment by xxmen** [comment]
申请加入, 有相关ML经验

**Comment by Miachol** [comment]
已经建立 GitHub team，后面项目将由大家来共同推荐和建设。

**Comment by hjuinj** [comment]
@Miachol 没有找到team
